name: Deploy to Hostinger via SSH

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 1. Mengambil kode terbaru
        uses: actions/checkout@v4

      - name: 2. Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: 3. Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: 4. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 5. Compile Front-End Assets
        run: |
          npm install
          npm run build

      - name: 6. Deploy via SSH (Rsync)
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          # PENTING: Sesuaikan 'domainanda.com' dengan nama domain asli Anda di Hostinger
          TARGET: "/home/u540774644/domains/lightgrey-cobra-541586.hostingersite.com//public_html/"
          EXCLUDE: "/.git/, /node_modules/, /.env, /deploy_key*"

      - name: 7. Menjalankan Perintah Artisan di Server Hostinger
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/u540774644/domains/lightgrey-cobra-541586.hostingersite.com//public_html/

            echo "--- Memulai Optimalisasi Laravel ---"

            # Membersihkan seluruh cache lama
            php7.4-cli artisan optimize:clear || php8.1-cli artisan optimize:clear || php8.2-cli artisan optimize:clear || php8.3-cli artisan optimize:clear || php artisan optimize:clear

            echo "--- Menjalankan Migrasi Database ---"

            # Jalankan migrasi dengan flag --force agar berjalan otomatis tanpa konfirmasi prompt y/n
            php7.4-cli artisan migrate --force || php8.1-cli artisan migrate --force || php8.2-cli artisan migrate --force || php8.3-cli artisan migrate --force || php artisan migrate --force

            echo "--- Optimalisasi Selesai! ---"
