name: Deploy to Hostinger

on:
  push:
    branches:
      - main # Sesuaikan dengan nama branch utama Anda (main/master)

jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 1. Mengambil kode terbaru
        uses: actions/checkout@v4

      - name: 2. Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # Sesuaikan dengan versi PHP di Hostinger Anda

      - name: 3. Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: 4. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 5. Compile Front-End Assets
        run: |
          npm install
          npm run build

      - name: 6. Sinkronisasi FTP ke Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/ # Pastikan diakhiri dengan garis miring (/)
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env.example
            README.md
